# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "puppet"

  config.vm.define "web" do |web|
    web.vm.box = "puppetlabs/centos-6.5-64-puppet"
    config.vm.box_check_update = false
  end

  config.vm.define "db" do |db|
    db.vm.box = "puppetlabs/centos-6.5-64-puppet"
    config.vm.box_check_update = false
  end
  
end
