# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

def common_puppet_config(puppet)
    puppet.hiera_config_path = 'hiera.yaml'
    puppet.working_directory = "/vagrant"
    puppet.module_path = %W(modules module-lib)
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "web" do |web|
    web.vm.box = "puppetlabs/centos-6.5-64-puppet"
    web.vm.box_check_update = false

    web.vm.provision "puppet" do |puppet|
      common_puppet_config(puppet)
      puppet.facter = {
        "machine_role" => "web"
      }
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "puppetlabs/centos-6.5-64-puppet"
    db.vm.box_check_update = false

    db.vm.provision "puppet" do |puppet|
      common_puppet_config(puppet)
      puppet.facter = {
        "machine_role" => "db"
      }
    end
  end

  config.vm.define 'ci' do |ci|
    ci.vm.box = "puppetlabs/centos-6.5-64-puppet"
    ci.vm.box_check_update = false
    ci.vm.network "forwarded_port", guest: 8153, host: 18153
    ci.vm.network "forwarded_port", guest: 8154, host: 18154

    ci.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    ci.vm.provision "puppet" do |puppet|
      common_puppet_config(puppet)
      puppet.facter = {
        "machine_role" => "ci_server"
      }
    end
  end

end
